// What this file is: generates public/favicon.svg from the exact same
// geometry AND the exact same drawing (the stroked mark paths, round caps
// and joins) that src/components/ui/Logo.tsx renders, sourced from
// src/lib/brandMark.ts. The only three things that differ from the header
// icon are things a favicon has no way around: a literal colour instead of
// an inherited `currentColor` (there's no parent element for a favicon to
// inherit from), its own background square (the header relies on the dark
// tile `App.tsx` draws around it; a favicon has no parent to draw that for
// it), and a slightly heavier stroke, because a favicon is rendered as small
// as 16px. Nothing about the shape itself is redrawn or reinterpreted.
// Run with `npm run build:favicon` after changing anything in
// brandMark.ts; it also runs automatically before `npm run build`.
// In plain terms: rebuilds the browser-tab icon as a direct copy of the
// header icon's drawing, so the two can never look different by accident.
//
// This script also rewrites index.html's <link rel="icon"> href to
// "/favicon.svg?v=<content hash>". Browsers cache favicons by URL and are
// notoriously unreliable about respecting normal cache-busting for them
// (some appear to key the cache by hostname rather than full origin, so
// even a fresh port doesn't guarantee a refetch) -- changing the URL itself
// whenever the content changes is the one thing that reliably works
// regardless of a given browser's specific favicon-caching quirks.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { MARK_FAVICON_STROKE_WIDTH, MARK_PATHS, MARK_VIEW_BOX } from '../src/lib/brandMark.ts';

const BG = '#0f172a';
const FG = '#fff';

// The mark is drawn on its own grid (see MARK_VIEW_BOX), so it goes into the
// 32x32 tile as a nested <svg> sized to the 24x24 content box -- the browser
// scales it, exactly as the header does.
const paths = MARK_PATHS.map((d) => `<path d="${d}" />`).join('\n      ');

const svg = `<!--
  What this file is: the browser-tab icon and app tile. Generated by
  scripts/build-favicon.ts from src/lib/brandMark.ts; do not hand-edit this
  file, run npm run build:favicon after changing that one instead.
  In plain terms: the little picture shown on the browser tab.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">
  <rect width="32" height="32" rx="7.5" fill="${BG}" />
  <svg x="4" y="4" width="24" height="24" viewBox="${MARK_VIEW_BOX}">
    <g fill="none" stroke="${FG}" stroke-width="${MARK_FAVICON_STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round">
      ${paths}
    </g>
  </svg>
</svg>
`;

const outPath = fileURLToPath(new URL('../public/favicon.svg', import.meta.url));
writeFileSync(outPath, svg);
console.log(`Wrote ${outPath}`);

const hash = createHash('sha1').update(svg).digest('hex').slice(0, 8);
const indexPath = fileURLToPath(new URL('../index.html', import.meta.url));
const indexHtml = readFileSync(indexPath, 'utf8');
const updatedIndexHtml = indexHtml.replace(
  /href="\/favicon\.svg(?:\?v=[0-9a-f]+)?"/,
  `href="/favicon.svg?v=${hash}"`,
);
if (updatedIndexHtml === indexHtml && !indexHtml.includes(`favicon.svg?v=${hash}`)) {
  throw new Error('build-favicon.ts: could not find the favicon <link> in index.html to update.');
}
writeFileSync(indexPath, updatedIndexHtml);
console.log(`Updated ${indexPath} to reference favicon.svg?v=${hash}`);
